terraform:
  version: ">= 1.3"
  required_providers:
    google:
      source: "hashicorp/google"
      version: "~> 4.0"
  backend:
    type: "local"
    path: "terraform.tfstate"

modules:
  networking:
    source: "./modules/networking"
    enabled: true
    variables:
      project_id: "durable-destiny-465315-u0"
      vpc_name: "my-vpc"
      auto_create_subnetworks: false
      routing_mode: "REGIONAL"
      environment: "dev"
      enable_nat: true
      name_prefix: "myproject-dev"
      region: "us-central1"
      nat_ip_allocate_option: "AUTO_ONLY"
      source_subnetwork_ip_ranges_to_nat: "ALL_SUBNETWORKS_ALL_IP_RANGES"
      nat_log_config:
        enable: true
        filter: "ALL"
      nat_subnetworks:
        - name: "subnet-1"
          source_ip_ranges_to_nat: ["ALL_IP_RANGES"]
      subnets:
        - name: "subnet-1"
          ip_cidr_range: "10.0.1.0/24"
          region: "us-central1"
          private_ip_google_access: true
          secondary_ip_ranges: []
          flow_logs_enabled: true
          flow_logs_config:
            aggregation_interval: "INTERVAL_5_SEC"
            flow_sampling: 0.5
            metadata: "INCLUDE_ALL_METADATA"

outputs:
  vpc_id:
    description: "The ID of the created VPC"
    value: module.networking.vpc_id
